-- Bootstrap router visibility + blank mapping templates for the four example forms.
-- Keep field lists in sync with app/forms/settings/formFieldCatalog.ts

INSERT INTO "router_forms" ("slug", "name", "visible") VALUES
  ('appointment-set', 'Appointment Set', TRUE),
  ('appointment-met', 'Appointment Met', TRUE),
  ('pending', 'Pending', TRUE),
  ('closed', 'Closed', TRUE)
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "form_sisu_mappings" ("form", "field_name", "sisu_field_name", "sisu_field_type", "custom", "enabled") VALUES
  ('pending', 'clientFirstName', NULL, NULL, FALSE, TRUE),
  ('pending', 'clientLastName', NULL, NULL, FALSE, TRUE),
  ('pending', 'clientPhone', NULL, NULL, FALSE, TRUE),
  ('pending', 'clientEmail', NULL, NULL, FALSE, TRUE),
  ('pending', 'clientType', NULL, NULL, FALSE, TRUE),
  ('pending', 'transactionStage', NULL, NULL, FALSE, TRUE),
  ('pending', 'transactionAmount', NULL, NULL, FALSE, TRUE),
  ('pending', 'addressLine1', NULL, NULL, FALSE, TRUE),
  ('pending', 'addressLine2', NULL, NULL, FALSE, TRUE),
  ('pending', 'city', NULL, NULL, FALSE, TRUE),
  ('pending', 'state', NULL, NULL, FALSE, TRUE),
  ('pending', 'postal', NULL, NULL, FALSE, TRUE),
  ('pending', 'agent2', NULL, NULL, FALSE, TRUE),
  ('pending', 'agent2Percent', NULL, NULL, FALSE, TRUE),
  ('pending', 'jcreOffice', NULL, NULL, FALSE, TRUE),
  ('pending', 'jcreLeadTransaction', NULL, NULL, FALSE, TRUE),
  ('pending', 'plrAcknowledgement', NULL, NULL, FALSE, TRUE),
  ('pending', 'closingDepartment', NULL, NULL, FALSE, TRUE),
  ('pending', 'hasSecondaryClient', NULL, NULL, FALSE, TRUE),
  ('pending', 'secondaryContact', NULL, NULL, FALSE, TRUE),
  ('pending', 'secondaryContactPhone', NULL, NULL, FALSE, TRUE),
  ('pending', 'secondaryContactEmail', NULL, NULL, FALSE, TRUE),
  ('pending', 'onTeam', NULL, NULL, FALSE, TRUE),
  ('pending', 'teamLeaderName', NULL, NULL, FALSE, TRUE),
  ('pending', 'teamPayNotes', NULL, NULL, FALSE, TRUE),
  ('pending', 'isaSet', NULL, NULL, FALSE, TRUE),
  ('pending', 'isaName', NULL, NULL, FALSE, TRUE),
  ('pending', 'pastClient', NULL, NULL, FALSE, TRUE),
  ('pending', 'underContractDate', NULL, NULL, FALSE, TRUE),
  ('pending', 'forecastedClosedDate', NULL, NULL, FALSE, TRUE),
  ('pending', 'outsideReferral', NULL, NULL, FALSE, TRUE),
  ('pending', 'referralPercent', NULL, NULL, FALSE, TRUE),
  ('pending', 'referralAmount', NULL, NULL, FALSE, TRUE),
  ('pending', 'referralMailingAddress', NULL, NULL, FALSE, TRUE),
  ('pending', 'otherAgentName', NULL, NULL, FALSE, TRUE),
  ('pending', 'otherAgentPhone', NULL, NULL, FALSE, TRUE),
  ('pending', 'otherAgentEmail', NULL, NULL, FALSE, TRUE),
  ('pending', 'otherAgentCompany', NULL, NULL, FALSE, TRUE),
  ('pending', 'closingAttorney', NULL, NULL, FALSE, TRUE),
  ('pending', 'closingAttorneyOther', NULL, NULL, FALSE, TRUE),
  ('pending', 'closingAttorneyPhone', NULL, NULL, FALSE, TRUE),
  ('pending', 'closingAttorneyEmail', NULL, NULL, FALSE, TRUE),
  ('pending', 'mortgageCompany', NULL, NULL, FALSE, TRUE),
  ('pending', 'mortgageCompanyName', NULL, NULL, FALSE, TRUE),
  ('pending', 'loanOfficerName', NULL, NULL, FALSE, TRUE),
  ('pending', 'loanOfficerEmail', NULL, NULL, FALSE, TRUE),
  ('pending', 'financingType', NULL, NULL, FALSE, TRUE),
  ('pending', 'dueDiligencePeriod', NULL, NULL, FALSE, TRUE),
  ('pending', 'dueDiligenceDeadline', NULL, NULL, FALSE, TRUE),
  ('pending', 'contingencies', NULL, NULL, FALSE, TRUE),
  ('pending', 'contingencyDetails', NULL, NULL, FALSE, TRUE),
  ('pending', 'multipleTransactions', NULL, NULL, FALSE, TRUE),
  ('pending', 'otherAddresses', NULL, NULL, FALSE, TRUE),
  ('pending', 'closingDepartmentNotes', NULL, NULL, FALSE, TRUE),
  ('pending', 'goodFundContribution', NULL, NULL, FALSE, TRUE),
  ('pending', 'commissionDelivery', NULL, NULL, FALSE, TRUE),
  ('pending', 'sellerCompensationPercent', NULL, NULL, FALSE, TRUE),
  ('pending', 'grossCommissionTotal', NULL, NULL, FALSE, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_sisu_mappings" ("form", "field_name", "sisu_field_name", "sisu_field_type", "custom", "enabled") VALUES
  ('appointmentSet', 'clientFirstName', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'clientLastName', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'clientPhone', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'clientEmail', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'leadType', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'apptSetBy', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'assignedIsa', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'assignedOsa', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'notes', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'appointmentDate', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'appointmentStartTime', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'appointmentEndTime', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'appointmentLocation', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'streetAddress', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'addressLine2', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'city', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'state', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'postalCode', NULL, NULL, FALSE, TRUE),
  ('appointmentSet', 'appointmentType', NULL, NULL, FALSE, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_sisu_mappings" ("form", "field_name", "sisu_field_name", "sisu_field_type", "custom", "enabled") VALUES
  ('appointmentMet', 'clientFirstName', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'clientLastName', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'clientPhone', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'clientEmail', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'leadType', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'agentSubmitting', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'apptDisposition', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'appointmentMetDate', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'apptOutcome', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'nextStep', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'notes', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'cancelledNextStep', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'followUpNotes', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'rescheduledDate', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'rescheduledStartTime', NULL, NULL, FALSE, TRUE),
  ('appointmentMet', 'rescheduledEndTime', NULL, NULL, FALSE, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_sisu_mappings" ("form", "field_name", "sisu_field_name", "sisu_field_type", "custom", "enabled") VALUES
  ('closed', 'transactionType', NULL, NULL, FALSE, TRUE),
  ('closed', 'addressLine1', NULL, NULL, FALSE, TRUE),
  ('closed', 'city', NULL, NULL, FALSE, TRUE),
  ('closed', 'state', NULL, NULL, FALSE, TRUE),
  ('closed', 'postal', NULL, NULL, FALSE, TRUE),
  ('closed', 'transactionAmount', NULL, NULL, FALSE, TRUE),
  ('closed', 'securityDeposit', NULL, NULL, FALSE, TRUE),
  ('closed', 'monthlyRent', NULL, NULL, FALSE, TRUE),
  ('closed', 'totalCommissionGci', NULL, NULL, FALSE, TRUE),
  ('closed', 'settlementDate', NULL, NULL, FALSE, TRUE),
  ('closed', 'tcMarketingNotes', NULL, NULL, FALSE, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_fub_person_mappings" ("form", "field_name", "fub_field_name", "enabled") VALUES
  ('pending', 'clientFirstName', NULL, TRUE),
  ('pending', 'clientLastName', NULL, TRUE),
  ('pending', 'clientPhone', NULL, TRUE),
  ('pending', 'clientEmail', NULL, TRUE),
  ('pending', 'clientType', NULL, TRUE),
  ('pending', 'transactionStage', NULL, TRUE),
  ('pending', 'transactionAmount', NULL, TRUE),
  ('pending', 'addressLine1', NULL, TRUE),
  ('pending', 'addressLine2', NULL, TRUE),
  ('pending', 'city', NULL, TRUE),
  ('pending', 'state', NULL, TRUE),
  ('pending', 'postal', NULL, TRUE),
  ('pending', 'agent2', NULL, TRUE),
  ('pending', 'agent2Percent', NULL, TRUE),
  ('pending', 'jcreOffice', NULL, TRUE),
  ('pending', 'jcreLeadTransaction', NULL, TRUE),
  ('pending', 'plrAcknowledgement', NULL, TRUE),
  ('pending', 'closingDepartment', NULL, TRUE),
  ('pending', 'hasSecondaryClient', NULL, TRUE),
  ('pending', 'secondaryContact', NULL, TRUE),
  ('pending', 'secondaryContactPhone', NULL, TRUE),
  ('pending', 'secondaryContactEmail', NULL, TRUE),
  ('pending', 'onTeam', NULL, TRUE),
  ('pending', 'teamLeaderName', NULL, TRUE),
  ('pending', 'teamPayNotes', NULL, TRUE),
  ('pending', 'isaSet', NULL, TRUE),
  ('pending', 'isaName', NULL, TRUE),
  ('pending', 'pastClient', NULL, TRUE),
  ('pending', 'underContractDate', NULL, TRUE),
  ('pending', 'forecastedClosedDate', NULL, TRUE),
  ('pending', 'outsideReferral', NULL, TRUE),
  ('pending', 'referralPercent', NULL, TRUE),
  ('pending', 'referralAmount', NULL, TRUE),
  ('pending', 'referralMailingAddress', NULL, TRUE),
  ('pending', 'otherAgentName', NULL, TRUE),
  ('pending', 'otherAgentPhone', NULL, TRUE),
  ('pending', 'otherAgentEmail', NULL, TRUE),
  ('pending', 'otherAgentCompany', NULL, TRUE),
  ('pending', 'closingAttorney', NULL, TRUE),
  ('pending', 'closingAttorneyOther', NULL, TRUE),
  ('pending', 'closingAttorneyPhone', NULL, TRUE),
  ('pending', 'closingAttorneyEmail', NULL, TRUE),
  ('pending', 'mortgageCompany', NULL, TRUE),
  ('pending', 'mortgageCompanyName', NULL, TRUE),
  ('pending', 'loanOfficerName', NULL, TRUE),
  ('pending', 'loanOfficerEmail', NULL, TRUE),
  ('pending', 'financingType', NULL, TRUE),
  ('pending', 'dueDiligencePeriod', NULL, TRUE),
  ('pending', 'dueDiligenceDeadline', NULL, TRUE),
  ('pending', 'contingencies', NULL, TRUE),
  ('pending', 'contingencyDetails', NULL, TRUE),
  ('pending', 'multipleTransactions', NULL, TRUE),
  ('pending', 'otherAddresses', NULL, TRUE),
  ('pending', 'closingDepartmentNotes', NULL, TRUE),
  ('pending', 'goodFundContribution', NULL, TRUE),
  ('pending', 'commissionDelivery', NULL, TRUE),
  ('pending', 'sellerCompensationPercent', NULL, TRUE),
  ('pending', 'grossCommissionTotal', NULL, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_fub_person_mappings" ("form", "field_name", "fub_field_name", "enabled") VALUES
  ('appointmentSet', 'clientFirstName', NULL, TRUE),
  ('appointmentSet', 'clientLastName', NULL, TRUE),
  ('appointmentSet', 'clientPhone', NULL, TRUE),
  ('appointmentSet', 'clientEmail', NULL, TRUE),
  ('appointmentSet', 'leadType', NULL, TRUE),
  ('appointmentSet', 'apptSetBy', NULL, TRUE),
  ('appointmentSet', 'assignedIsa', NULL, TRUE),
  ('appointmentSet', 'assignedOsa', NULL, TRUE),
  ('appointmentSet', 'notes', NULL, TRUE),
  ('appointmentSet', 'appointmentDate', NULL, TRUE),
  ('appointmentSet', 'appointmentStartTime', NULL, TRUE),
  ('appointmentSet', 'appointmentEndTime', NULL, TRUE),
  ('appointmentSet', 'appointmentLocation', NULL, TRUE),
  ('appointmentSet', 'streetAddress', NULL, TRUE),
  ('appointmentSet', 'addressLine2', NULL, TRUE),
  ('appointmentSet', 'city', NULL, TRUE),
  ('appointmentSet', 'state', NULL, TRUE),
  ('appointmentSet', 'postalCode', NULL, TRUE),
  ('appointmentSet', 'appointmentType', NULL, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_fub_person_mappings" ("form", "field_name", "fub_field_name", "enabled") VALUES
  ('appointmentMet', 'clientFirstName', NULL, TRUE),
  ('appointmentMet', 'clientLastName', NULL, TRUE),
  ('appointmentMet', 'clientPhone', NULL, TRUE),
  ('appointmentMet', 'clientEmail', NULL, TRUE),
  ('appointmentMet', 'leadType', NULL, TRUE),
  ('appointmentMet', 'agentSubmitting', NULL, TRUE),
  ('appointmentMet', 'apptDisposition', NULL, TRUE),
  ('appointmentMet', 'appointmentMetDate', NULL, TRUE),
  ('appointmentMet', 'apptOutcome', NULL, TRUE),
  ('appointmentMet', 'nextStep', NULL, TRUE),
  ('appointmentMet', 'notes', NULL, TRUE),
  ('appointmentMet', 'cancelledNextStep', NULL, TRUE),
  ('appointmentMet', 'followUpNotes', NULL, TRUE),
  ('appointmentMet', 'rescheduledDate', NULL, TRUE),
  ('appointmentMet', 'rescheduledStartTime', NULL, TRUE),
  ('appointmentMet', 'rescheduledEndTime', NULL, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_fub_person_mappings" ("form", "field_name", "fub_field_name", "enabled") VALUES
  ('closed', 'transactionType', NULL, TRUE),
  ('closed', 'addressLine1', NULL, TRUE),
  ('closed', 'city', NULL, TRUE),
  ('closed', 'state', NULL, TRUE),
  ('closed', 'postal', NULL, TRUE),
  ('closed', 'transactionAmount', NULL, TRUE),
  ('closed', 'securityDeposit', NULL, TRUE),
  ('closed', 'monthlyRent', NULL, TRUE),
  ('closed', 'totalCommissionGci', NULL, TRUE),
  ('closed', 'settlementDate', NULL, TRUE),
  ('closed', 'tcMarketingNotes', NULL, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_fub_deal_mappings" ("form", "field_name", "fub_field_name", "enabled") VALUES
  ('pending', 'clientFirstName', NULL, TRUE),
  ('pending', 'clientLastName', NULL, TRUE),
  ('pending', 'clientPhone', NULL, TRUE),
  ('pending', 'clientEmail', NULL, TRUE),
  ('pending', 'clientType', NULL, TRUE),
  ('pending', 'transactionStage', NULL, TRUE),
  ('pending', 'transactionAmount', NULL, TRUE),
  ('pending', 'addressLine1', NULL, TRUE),
  ('pending', 'addressLine2', NULL, TRUE),
  ('pending', 'city', NULL, TRUE),
  ('pending', 'state', NULL, TRUE),
  ('pending', 'postal', NULL, TRUE),
  ('pending', 'agent2', NULL, TRUE),
  ('pending', 'agent2Percent', NULL, TRUE),
  ('pending', 'jcreOffice', NULL, TRUE),
  ('pending', 'jcreLeadTransaction', NULL, TRUE),
  ('pending', 'plrAcknowledgement', NULL, TRUE),
  ('pending', 'closingDepartment', NULL, TRUE),
  ('pending', 'hasSecondaryClient', NULL, TRUE),
  ('pending', 'secondaryContact', NULL, TRUE),
  ('pending', 'secondaryContactPhone', NULL, TRUE),
  ('pending', 'secondaryContactEmail', NULL, TRUE),
  ('pending', 'onTeam', NULL, TRUE),
  ('pending', 'teamLeaderName', NULL, TRUE),
  ('pending', 'teamPayNotes', NULL, TRUE),
  ('pending', 'isaSet', NULL, TRUE),
  ('pending', 'isaName', NULL, TRUE),
  ('pending', 'pastClient', NULL, TRUE),
  ('pending', 'underContractDate', NULL, TRUE),
  ('pending', 'forecastedClosedDate', NULL, TRUE),
  ('pending', 'outsideReferral', NULL, TRUE),
  ('pending', 'referralPercent', NULL, TRUE),
  ('pending', 'referralAmount', NULL, TRUE),
  ('pending', 'referralMailingAddress', NULL, TRUE),
  ('pending', 'otherAgentName', NULL, TRUE),
  ('pending', 'otherAgentPhone', NULL, TRUE),
  ('pending', 'otherAgentEmail', NULL, TRUE),
  ('pending', 'otherAgentCompany', NULL, TRUE),
  ('pending', 'closingAttorney', NULL, TRUE),
  ('pending', 'closingAttorneyOther', NULL, TRUE),
  ('pending', 'closingAttorneyPhone', NULL, TRUE),
  ('pending', 'closingAttorneyEmail', NULL, TRUE),
  ('pending', 'mortgageCompany', NULL, TRUE),
  ('pending', 'mortgageCompanyName', NULL, TRUE),
  ('pending', 'loanOfficerName', NULL, TRUE),
  ('pending', 'loanOfficerEmail', NULL, TRUE),
  ('pending', 'financingType', NULL, TRUE),
  ('pending', 'dueDiligencePeriod', NULL, TRUE),
  ('pending', 'dueDiligenceDeadline', NULL, TRUE),
  ('pending', 'contingencies', NULL, TRUE),
  ('pending', 'contingencyDetails', NULL, TRUE),
  ('pending', 'multipleTransactions', NULL, TRUE),
  ('pending', 'otherAddresses', NULL, TRUE),
  ('pending', 'closingDepartmentNotes', NULL, TRUE),
  ('pending', 'goodFundContribution', NULL, TRUE),
  ('pending', 'commissionDelivery', NULL, TRUE),
  ('pending', 'sellerCompensationPercent', NULL, TRUE),
  ('pending', 'grossCommissionTotal', NULL, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_fub_deal_mappings" ("form", "field_name", "fub_field_name", "enabled") VALUES
  ('appointmentSet', 'clientFirstName', NULL, TRUE),
  ('appointmentSet', 'clientLastName', NULL, TRUE),
  ('appointmentSet', 'clientPhone', NULL, TRUE),
  ('appointmentSet', 'clientEmail', NULL, TRUE),
  ('appointmentSet', 'leadType', NULL, TRUE),
  ('appointmentSet', 'apptSetBy', NULL, TRUE),
  ('appointmentSet', 'assignedIsa', NULL, TRUE),
  ('appointmentSet', 'assignedOsa', NULL, TRUE),
  ('appointmentSet', 'notes', NULL, TRUE),
  ('appointmentSet', 'appointmentDate', NULL, TRUE),
  ('appointmentSet', 'appointmentStartTime', NULL, TRUE),
  ('appointmentSet', 'appointmentEndTime', NULL, TRUE),
  ('appointmentSet', 'appointmentLocation', NULL, TRUE),
  ('appointmentSet', 'streetAddress', NULL, TRUE),
  ('appointmentSet', 'addressLine2', NULL, TRUE),
  ('appointmentSet', 'city', NULL, TRUE),
  ('appointmentSet', 'state', NULL, TRUE),
  ('appointmentSet', 'postalCode', NULL, TRUE),
  ('appointmentSet', 'appointmentType', NULL, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_fub_deal_mappings" ("form", "field_name", "fub_field_name", "enabled") VALUES
  ('appointmentMet', 'clientFirstName', NULL, TRUE),
  ('appointmentMet', 'clientLastName', NULL, TRUE),
  ('appointmentMet', 'clientPhone', NULL, TRUE),
  ('appointmentMet', 'clientEmail', NULL, TRUE),
  ('appointmentMet', 'leadType', NULL, TRUE),
  ('appointmentMet', 'agentSubmitting', NULL, TRUE),
  ('appointmentMet', 'apptDisposition', NULL, TRUE),
  ('appointmentMet', 'appointmentMetDate', NULL, TRUE),
  ('appointmentMet', 'apptOutcome', NULL, TRUE),
  ('appointmentMet', 'nextStep', NULL, TRUE),
  ('appointmentMet', 'notes', NULL, TRUE),
  ('appointmentMet', 'cancelledNextStep', NULL, TRUE),
  ('appointmentMet', 'followUpNotes', NULL, TRUE),
  ('appointmentMet', 'rescheduledDate', NULL, TRUE),
  ('appointmentMet', 'rescheduledStartTime', NULL, TRUE),
  ('appointmentMet', 'rescheduledEndTime', NULL, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

INSERT INTO "form_fub_deal_mappings" ("form", "field_name", "fub_field_name", "enabled") VALUES
  ('closed', 'transactionType', NULL, TRUE),
  ('closed', 'addressLine1', NULL, TRUE),
  ('closed', 'city', NULL, TRUE),
  ('closed', 'state', NULL, TRUE),
  ('closed', 'postal', NULL, TRUE),
  ('closed', 'transactionAmount', NULL, TRUE),
  ('closed', 'securityDeposit', NULL, TRUE),
  ('closed', 'monthlyRent', NULL, TRUE),
  ('closed', 'totalCommissionGci', NULL, TRUE),
  ('closed', 'settlementDate', NULL, TRUE),
  ('closed', 'tcMarketingNotes', NULL, TRUE)
ON CONFLICT ("form", "field_name") DO NOTHING;

